#!/usr/bin/env bash

set -eu

INCLUDE_EXTENSIONS=(
  "*.encrypted.*"
)

ENCRYPTION_INFIX=".encrypted"

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

FIND_ARGS=("$REPO_ROOT" -type f "(")
for i in "${!INCLUDE_EXTENSIONS[@]}"; do
  if [ $i -gt 0 ]; then
    FIND_ARGS+=( -o )
  fi

  FIND_ARGS+=( -name "${INCLUDE_EXTENSIONS[i]}" )
done
FIND_ARGS+=( ")" )

while read -r FILE; do

    TARGET_FILE="${FILE%$ENCRYPTION_INFIX*}.${FILE##*.}"
    sops -d "$FILE" > "$TARGET_FILE"

done < <(find "${FIND_ARGS[@]}")