name: smarthome

networks:
  internal:
    name: smarthome_internal
    driver: bridge
  macvlan:
    name: macvlan
    external: true
  traefik:
    name: traefik
    external: true

services:
  nanomq:
    image: emqx/nanomq:0.24.13
    container_name: nanoMQ
    hostname: nanoMQ
    networks:
      internal:
        aliases:
          - mqtt
    environment:
      NANOMQ_NUM_TASKQ_THREAD: 4
      NANOMQ_MAX_TASKQ_THREAD: 4
      NANOMQ_PARALLEL: 8
      NANOMQ_MSQ_LEN: 65535
    restart: unless-stopped
    labels:
      backup.enable: true
      backup.mode: live
    
  nodeRED:
    image: nodered/node-red:4.1.8-22
    container_name: nodeRED
    hostname: nodeRED
    networks:
      internal:
      macvlan:
        ipv4_address: ${NODERED_IP:?error}
        mac_address: ${NODERED_MAC:?error}        
      traefik:
    environment:
      TZ: Europe/Berlin
    volumes:
      - nodered_data:/data
    restart: unless-stopped
    labels:
      backup.enable: true
      backup.mode: live
      traefik.enable: true
      traefik.http.routers.nodeRED.rule: Host(`${NODERED_DOMAIN:?error}`)
      traefik.http.routers.nodeRED.priority: 65
      traefik.http.routers.nodeRED.entrypoints: websecure
      traefik.http.routers.nodeRED.middlewares: local-ip-allow-list@file
      traefik.http.services.nodeRED.loadbalancer.server.port: 1880

  zigbee:
    image: koenkk/zigbee2mqtt:2.9.2
    container_name: zigbee
    networks:
      internal:
        aliases:
          - zigbee
      traefik:
    environment:
      TZ: Europe/Berlin
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_40c39dadcb93eb1194021b4f3d98b6d1-if00-port0:/dev/zigbee
    volumes:
      - zigbee_data:/app/data
    restart: unless-stopped
    labels:
      backup.enable: true
      backup.mode: live
      traefik.enable: true
      traefik.http.routers.zigbee.rule: Host(`${ZIGBEE_DOMAIN:?error}`)
      traefik.http.routers.zigbee.priority: 65
      traefik.http.routers.zigbee.entrypoints: websecure
      traefik.http.routers.zigbee.middlewares: local-ip-allow-list@file
      traefik.http.services.zigbee.loadbalancer.server.port: 80

volumes:
  nodered_data:
  zigbee_data: