name: microsoft-kms

networks:
  lan:
    name: macvlan
    external: true

services:
  vlmcsd:
    image: ghcr.io/miscos/vlmcsd-docker:latest
    container_name: microsoft-kms
    networks:
      lan:
        ipv4_address: ${KMS_IP:?error}
        mac_address: ${KMS_MAC:?error}
    restart: unless-stopped