name: navidrome

networks:
  netbird:
    name: netbird
    external: true
  traefik:
    name: traefik
    external: true

services:
  navidrome:
    image: deluan/navidrome:0.62.0
    container_name: navidrome
    networks:
      netbird:
        ipv4_address: ${NAVIDROME_NETBIRD_IP:?error}
      traefik:
    expose:
      - "4533"
    environment:
      ND_LOGLEVEL: debug
      ND_EXTAUTH_TRUSTEDSOURCES: ${NETBIRD_IP_RANGE:?error}
      ND_ENABLEINSIGHTSCOLLECTOR: false
    volumes:
      - "data:/data"
      - "music:/music:ro"
    restart: unless-stopped
    labels:
      backup.enable: true
      backup.mode: live
      traefik.enable: true
      traefik.http.routers.navidrome.rule: Host(`${NAVIDROME_DOMAIN:?error}`)
      traefik.http.routers.navidrome.priority: 50
      traefik.http.routers.navidrome.entrypoints: websecure
      traefik.http.services.navidrome.loadbalancer.server.port: 4533

volumes:
  data:
  music:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.10.201,nolock,soft,rw"
      device: ":/mnt/SSD/Media/Music"