http:
  # MIDDLEWARES
  middlewares:
    # Local IPs Allowlist
    local-ip-allow-list:
      plugin:
        ddns-allowlist:
          sourceRangeHosts:
            - ENC[AES256_GCM,data:ns525hOvNa3hVG2rdR7QSHJSk5lVfq5Q,iv:OAmIDIY4G/LwSzLlomXGOyh9xQa7NdZZu4pV14VPdR8=,tag:VAUZOto+m2cgJ6NPOTaRvA==,type:str]
          sourceRangeIps:
            - 127.0.0.1/32
            - 172.20.0.0/16
            - 10.0.0.0/16
    # Error pages
    errorpages:
      errors:
        status:
          - 400-599
        service: errorpages@docker
        query: /{status}.html
  # ROUTERS
  routers:
    # AdGuard
    adguard:
      rule: ENC[AES256_GCM,data:KHVk/w228rDttS9srk5UnfXEOnXxII77rLLG5Qy0vUcskoEbHM36jAwLsnnDyZRXywEr1iuTYyu4,iv:CAe9bapVBZ2qyZuSu/HAhcLk+pe5289nn4Erfd4PiHI=,tag:UgXLFlsgJVT4UqtlCsL9PQ==,type:str]
      entryPoints:
        - websecure
      middlewares:
        - local-ip-allow-list@file
      service: adguard@file
    # forgejo
    forgejo:
      rule: ENC[AES256_GCM,data:HQkcBOeNiOdWK+j81D1RbSyDPen7CwPzoTvWVR5BnWbSKa417jNX2G7ClsCCr47BKs4Bmg==,iv:2VQU46kefbt9smQzPpIlxj+qoMRdW4NH6xVwnBIS0gY=,tag:KkZn3JHlxff81Fv9g629hw==,type:str]
      entryPoints:
        - websecure
      middlewares:
        - local-ip-allow-list@file
      service: forgejo@file
    # TrueNAS
    truenas:
      rule: ENC[AES256_GCM,data:DHXSZjE/KHdpIdqrokosgIA8pYVNky03CNu0A7J5iEx0L1+t0ACB0TOxRj8koSnZMl9HWgRDpvc1OA==,iv:VqTnLvmFlLyS39NJjBpOjHXKnSkiT6WN6Xv1i3EOzvA=,tag:b4nH+KXo8TNHKSE26gJDtA==,type:str]
      entryPoints:
        - websecure
      middlewares:
        - local-ip-allow-list@file
      service: truenas@file
    # Proxmox
    proxmox:
      rule: ENC[AES256_GCM,data:cxGyBChHF9IW/1ScZbYY77j3QJCxa9yt8kP/nnBn8K/W5OrDLWBGbzGZzgWwK9fhr6wRhBHEr9sXjA==,iv:bkkzIwoKxUigsRvsYlBspuohPhxlltFfYcwFOQLyWcM=,tag:CV0gNiViJS3m/gjQnfBQkw==,type:str]
      entryPoints:
        - websecure
      middlewares:
        - local-ip-allow-list@file
      service: proxmox@file
  # SERVICES
  services:
    # AdGuard
    adguard:
      loadBalancer:
        servers:
          - url: ENC[AES256_GCM,data:nOqi6P0bv6oLRs6X3OwBIKwFdHc8,iv:O4/j2qsLeQcU+pT6z0oLqx1APZtyRACosavOSHs2A/w=,tag:4/SOkz4fiA5QLbP997+GgA==,type:str]
    # forgejo
    forgejo:
      loadBalancer:
        servers:
          - url: ENC[AES256_GCM,data:pRdlEdrq/pV/fDkVHkzLryy29WuBNE0=,iv:2VwTyE/McQnRyqtHhqqWxrfPqduvoGgEiJREaVa8ZZo=,tag:JiVPWH8pyhx4HVtJv9ifZw==,type:str]
    # TrueNAS
    truenas:
      loadBalancer:
        servers:
          - url: ENC[AES256_GCM,data:4hm3IRdpmd+MsKv0QavaNtmN9Q27,iv:QMi6RWk3FZF/zrtnKjeq08r/RNoMiBdyPz5vBhqyjRI=,tag:33t2xqJ1fCkTIoAjfsQZ/w==,type:str]
        passHostHeader: true
    # Proxmox
    proxmox:
      loadBalancer:
        serversTransport: insecure
        servers:
          - url: ENC[AES256_GCM,data:VWXDM5+MyQWWGV6ptYG9KN613lM9lw==,iv:GOxDa21XjES9F7HhqjdtGF6H85xxIqlyzcpf9JPujZU=,tag:HuqOFQri4SjEnJ0avCudkQ==,type:str]
  # SERVERS TRANSPORTS
  serversTransports:
    # Allow self signed certificates
    insecure:
      insecureSkipVerify: true
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEOyhQmd/dcUEfjHT4dXkgjEQqXY7GdRYU40QMNJ3wPi misc.OS@LENOVO-T14s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHUyRnZlQSBTY3hH
        V0FSSXF4aTVCTURHTGE2anZSQnB4bFEzMTJFRFZOQTZNN0d6SUdRCjhyM1FjNG04
        eVBkWVlJTjlSdkFZeEZTZ1FJMHorNFlHVUpWMVp6RlZncHcKLS0tIFhpWVRZVjhN
        eGFad0pjTWJ3VmZvRmlOZzVNL0dEZGxPWGllWWZSNXdXYjQKAsSp4P81EBJ0iqMN
        TtlIJue/eB6Pp2OUK1bbDMMllBTDYJ30a1O7SVl/j+UTldPTyUrxIZHydGsiLJ5R
        c7JNLQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEJdJx9MsCQN5i6lizRUUo5DkFhPm+3K/VjqDUeNL9hH ATLAS@VM.docker
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGtRM0Q0ZyBlUUxv
        R2ZtMjExaWh2U3laSzROMFpiKzhHRjNZdFVkYjhkb0pnZW5LYURBCjcrRHJNUzE2
        Sm5zZkpYTTdXVWtOSHE4dGlRU1JtYTJ3T1ZCT3VSUVFYTEUKLS0tIGo3U0RoWlNu
        eDlzMEM2OHVENS9IYktPd0FlNU9GOE9KMTZlNVh3ZlRjYlkKvIo/IN+0GVjrzD5U
        DLOW6fgWUgS1QAbsnUeyv6FFpGCPPTm3SDLsGG9eEU9qynP2rkgjoXX31nh4I2Rr
        Kk41rg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-13T12:39:51Z"
  mac: ENC[AES256_GCM,data:uTWidoypMwnV9O0U5zoZU719+ARbNZyibouZO27MhH0P3vmlGfUqTZKYnixiQ8iOCpHR5zvMrNip3YkO2lTxR8Rs8NBhA+7Cm832u0DG6PYp59+qzIdurMduSeUpHL/CxY7e/vp/1SSQhPAAG6wJ6x4moZbeTTvoW2KnrO6t8kg=,iv:2LBunSleqLfigtjvf+WtUnWfSvCJttnhwP7gus/e3Wg=,tag:pGx7y1pNtvFiZRLCB6ghJA==,type:str]
  encrypted_regex: (?i)password|key|token|secret|email|domain|uri|url|api_endpoint|issuer|authority|exposed|sourceRangeHosts|expression|rule
  version: 3.12.2
