name: nautilus

networks:
  netbird:
    name: netbird
    external: true

services:
  nautilus-ci:
    image: ghcr.io/miscos/nautilus-ci:1.0.1
    container_name: nautilus-ci
    networks:
      netbird:
        ipv4_address: ${NAUTILUS_NETBIRD_IP:?error}
    group_add:
      - ${DOCKER_GROUP_ID:?error} # Add the container to the docker group to allow access to the Docker socket
    environment:
      PORT: ${NAUTILUS_PORT:?error}
      GIT_BASE_DIRECTORY: "/home/ubuntu/gitops-docker-atlas/"
      GIT_WEBHOOK_SECRET: ${GIT_WEBHOOK_SECRET:?error}
      IGNORED_SUBDIRECTORIES: nautilus-ci
    volumes:
      - /home/ubuntu/.ssh/:/user/.ssh/:ro
      - /home/ubuntu/gitops-docker-atlas:/home/ubuntu/gitops-docker-atlas:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
