name: adguard

volumes:
  conf:
  data:

networks:
  lan:
    name: macvlan
    external: true
  traefik:
    name: traefik
    external: true

services:
  adguard:
    image: adguard/adguardhome:v0.107.74
    container_name: AdGuard
    hostname: AdGuard.VM.Atlas
    networks:
      lan:
        ipv4_address: 10.0.100.10
        ipv6_address: fddd:d0::100:10
        mac_address: 10:01:00:00:01:00
      traefik:
    volumes:
      - conf:/opt/adguardhome/conf
      - data:/opt/adguardhome/work
    restart: unless-stopped
    labels:
      backup.enable: true
      backup.mode: live
      traefik.enable: true
      traefik.http.routers.adguard.rule: Host(`adguard.${DOMAIN:?error}`)
      traefik.http.routers.adguard.priority: 90
      traefik.http.routers.adguard.entrypoints: websecure
      traefik.http.routers.adguard.middlewares: local-ip-allow-list@file
      traefik.http.services.adguard.loadbalancer.server.port: 80

